# This feedstock is used in jaxlib to ensure that we stay inside the CI limit.
# To find the correct version to build, browse https://github.com/google/jax/blob/jaxlib-v{{ version }}/third_party/xla/workspace.bzl
# to find the XLA commit used in the JAX release. Then you can find the LLVM
# commit in https://github.com/openxla/xla/blob/<xla_commit>/third_party/llvm/workspace.bzl
# It can also be useful for Tensorflow but it would there mainly reduce the 
# time in the local builds but won't help us fit the builds into the 6h window.
{% set version = "18.0.0.jax0423_cd9a64" %}
{% set major_ver = version.split(".")[0] %}
{% set git_commit = "cd9a641613eddf25d4b25eaa96b2c393d401d42c" %}
{% if git_commit != "" %}
  {% set archive_file = git_commit %}
{% else %}
  {% set archive_file = "refs/tags/llvmorg-" + version.replace(".rc", "-rc") %}
{% endif %}

package:
  name: llvm-bazel-cache
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/{{ archive_file }}.tar.gz
  sha256: 1495301b0048da51b189a30434a834a73b079e6092b5c614c9f257ee1ffe0a43
  patches:
    # Taken from https://github.com/openxla/xla/tree/fa9331a7e557b4ec1381f84cbbf7401a8f41ac66/third_party/llvm
    - patches/build.patch
    - patches/mathextras.patch
    - patches/toolchains.patch
    - patches/zstd.patch

build:
  number: 1
  skip: true  # [win]
  # conda-build breaks on this. There is no need to relocate anything, so skip it.
  binary_relocation: false

requirements:
  build:
    - python *
    - astor
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
    - bazel-toolchain
    - rsync
  run_constrained:
    # These packages provide the same static libraries
    - llvmdev <0a0
    - mlir <0a0

test:
  commands:
    - test -f "${PREFIX}/lib/libLLVMTFSupport.a"
    - test -f "${PREFIX}/share/llvm-bazel-cache/llvm/BUILD.bazel"
    - test -f "${PREFIX}/share/llvm-bazel-cache/llvm/include/llvm/Pass.h"
    - test -f "${PREFIX}/lib/libMLIRTFSupport.a"
    - test -f "${PREFIX}/share/llvm-bazel-cache/mlir/BUILD.bazel"
    - test -f "${PREFIX}/share/llvm-bazel-cache/mlir/include/mlir/InitAllPasses.h"

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  license: Apache-2.0 WITH LLVM-exception
  license_file: llvm/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM, pre-built for use with tensorflow

extra:
  recipe-maintainers:
    - conda-forge/tensorflow
